# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GAD Mediation Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GAD Mediation Demo
pod 'GoogleMobileAds-HyBid-Adapters', '2.5.1.0'
end
